initial commit
msmkdenis/go-rest-api-homework pull request #1
Opened 2023-11-28 14:12 UTC by msmkdenis

2023-12-04 13:09 UTC, robotomize requested changes
Отличная образцовая работа, вы хорошо поработали и применили DDD подход, мне работа очень понравилось без сомнения. Поправьте статус в одном месте и закрытие Body, все остальное выполнено очень круто. Спасибо

2023-12-04 13:09 UTC, robotomize commented on internal/handlers/task_handlers.go
> +		http.Error(w, "Unable to write response", http.StatusBadRequest)
Тут скорее всего ошиблись статус InternalSrverError

2023-12-04 13:09 UTC, robotomize commented on internal/handlers/task_handlers.go
> +	tasksDto := make([]dto.TaskResponse, 0, len(tasks))
Отлично, подумал про аллокацию заранее

2023-12-04 13:09 UTC, robotomize commented on internal/handlers/task_handlers.go
> +	if contentHeader != "application/json" {
Отлично

2023-12-04 13:09 UTC, robotomize commented on internal/handlers/task_handlers.go
> +type TaskHandlers struct {
Круто, что сделали отдельную структуру с методами +

2023-12-04 13:09 UTC, robotomize commented on internal/handlers/task_handlers.go
> +type TaskService interface {
Интерфейс в точке использования, отличная работа с абстракциями

2023-12-04 13:09 UTC, robotomize commented on internal/service/task_service.go
> +type TaskRepository interface {
Отлично, что подумали об абстракциях, несмотря на то, что сервис здесь получился немного простой это хороший задел на будущее

2023-12-04 13:09 UTC, robotomize commented on internal/app/app.go
> +func TaskManagerRun() {
Отличная точка инициализации зависимостей, единственно, что она блокирующая, это может быть проблемой при нескольких блокирующих сервисах в будущем, возможно http.Server можо также вынести в зависимость и стартовать в отдельной горутине в main

2023-12-04 13:09 UTC, robotomize commented on cmd/task_manager/precode.go
> +	app.TaskManagerRun()
Круто, можно добавить еще обработку сигналов и пробрасывать context, чтобы при вызове сигнала завершения процесса ваш сервис мягко останавливал работу

2023-12-04 13:09 UTC, robotomize commented on internal/handlers/task_handlers_test.go
> +			request := httptest.NewRequest(test.method, test.path, strings.NewReader(test.body))
Супер, что разобрались с httptst

2023-12-04 13:09 UTC, robotomize commented on internal/repository/memory/mem_task_storage.go
> +	r.mu.RLock()
Отличная работа с локами, круто, что поудмали о read lock и lock contention в решении

2023-12-04 13:09 UTC, robotomize commented on internal/apperrors/apperrors.go
> +func NewValueError(caller string, err error) error {
Хорошо сделано, но можно сделать отдельную ошибку с коллером внутри, тогда мы сможем не пробрасывать коллер а оборачивать ошибку в ошибк коллера, это может быть удобнее в ряде случаев

2023-12-06 08:36 UTC, msmkdenis commented on internal/handlers/task_handlers.go
> +		http.Error(w, "Unable to write response", http.StatusBadRequest)
Скорректировал

2023-12-06 08:56 UTC, msmkdenis commented
> Отличная образцовая работа, вы хорошо поработали и применили DDD подход, мне работа очень понравилось без сомнения. Поправьте статус один и все остальное выполнено очень круто. Спасибо!

Спасибо за комментарии! Поправил статус, закрыл body, дополнительные улучшение наверное буду делать дальше если продолжится работа над этим проектом ))

2023-12-06 08:57 UTC, msmkdenis commented
Спасибо за комментарии! Поправил статус, закрыл body, дополнительные улучшение наверное буду делать дальше если продолжится работа над этим проектом ))

2023-12-06 14:24 UTC, robotomize commented on .github/workflows/tests.yml
> +        run: go test -race -tags fast -v ./...
Отлично что разобрались с тегами!

2023-12-06 14:27 UTC, robotomize commented on .golangci.yml
> +# options for analysis running
Круто, что прикрутили линтер, попробуйте еще поиграть с линтерами, которые добавляются. Рассмотрите линтер, который проверяет выравнивание в структурах, заодно разберетесь как он работает и какие вещи можно решать выравниванием или например ускорять код попадая в кеш линию процессора
Можно еще поставить утилиту vulncheck https://go.dev/blog/vuln посмотреть для чего нужна и тд

2023-12-06 14:28 UTC, robotomize approved these changes
Отличная работа! Коллекцию Postman заценил, отлично, добный инстурмент еще хочу порекоммендовать разобраться с curl, часто нужно быстро что-то првоерять и с jq где пможно фильтроватьи  группировать по JSON

2024-01-30 16:17 UTC, merged